language: elixir
branches:
  only:
    - "master"
cache:
  directories:
    - deps
    - _build
matrix:
  include:
    - elixir: 1.10.3
      otp_release: 22.3.3
      env: COVERALLS=true CREDO=true
    - elixir: 1.9.4
      otp_release: 22.3.3
    - elixir: 1.8.2
      otp_release: 22.3.3
    - elixir: 1.7.4
      otp_release: 22.3.3
    - elixir: 1.6.6
      otp_release: 20.3
    - elixir: 1.5.3
      otp_release: 20.2
services:
  - docker
env:
  global:
    - COVERALLS=false
    - CREDO=false
before_script:
  - ./scripts/docker_up.sh
script:
  - MIX_ENV=test mix deps.compile
  - MIX_ENV=test mix compile --warnings-as-errors
  - ./scripts/ci_tests.sh
