language: elixir
otp_release:
  - 18.3
  - 19.2
elixir:
  - 1.4.0
  - 1.3.4
  - 1.2.6
  - 1.1.1
matrix:
  exclude:
    - elixir: 1.1.1
      otp_release: 19.2
    - elixir: 1.4.0
      otp_release: 19.2
      env: COVERALLS=false
  include:
    - elixir: 1.1.1
      otp_release: 17.5
    - elixir: 1.4.0
      otp_release: 19.2
      env: COVERALLS=true
sudo: required
services:
  - docker
env:
  - COVERALLS=false
cache:
  directories:
    - ~/kafka
before_script:
  - ./scripts/docker_up.sh
script:
  - MIX_ENV=test mix deps.compile
  - ./scripts/ci_tests.sh
