language: elixir
elixir:
  - 1.0.4
sudo: false
before_script:
  - ./install_kafka.sh
script:
  - mix test --include integration --include consumer_group; mix test --include integration --include consumer_group
