name: CI Tests

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  setup:
    name: test / setup
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: "v1.9"
            otp: "22"
          - elixir: "v1.10"
            otp: "23"
          - elixir: "v1.12"
            otp: "24"
    env:
      MIX_ENV: test

    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
          otp-version: ${{matrix.otp}} # Define the OTP version [required]
      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2
        id: mix-cache # id to use in retrieve action
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Compilation Cache
        uses: actions/cache@v2
        id: mix-deps-compile-cache # id to use in retrieve action
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-deps-compile-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
      - name: Install Mix Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get

      - name: Compile Mix Dependencies
        if: steps.mix-deps-compile-cache.outputs.cache-hit != 'true'
        run: mix deps.compile

  test:
    name: runner / Test
    needs: [setup]

    runs-on: ubuntu-20.04
    env:
      MIX_ENV: test

    strategy:
      fail-fast: false
      matrix:
        tests:
          - mix test --include integration
          - mix test --include consumer_group
          - mix test --include server_0_p_10_and_later
          - mix test --include server_0_p_10_p_1
          - mix test --include server_0_p_9_p_0
          - mix test --include server_0_p_8_p_0
          - mix test --include new_client
          - mix test

        include:
          - elixir: "v1.9"
            otp: "22"
          - elixir: "v1.10"
            otp: "23"
          - elixir: "v1.12"
            otp: "24"

    steps:
      - uses: actions/checkout@v2
      - name: Docker-compose up
        run: ./scripts/docker_up.sh
      - name: Setup elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{matrix.elixir}} # Define the elixir version [required]
          otp-version: ${{matrix.otp}} # Define the OTP version [required]

      - name: Retrieve Mix Dependencies Cache
        uses: actions/cache@v2
        id: mix-cache # id to use in retrieve action
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Retrieve Mix Dependencies Compilation Cache
        uses: actions/cache@v2
        id: mix-deps-compile-cache # id to use in retrieve action
        with:
          path: _build
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-deps-compile-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}

      - name: Docker ps
        run: docker ps
      - name: Run Tests
        run: ${{ matrix.tests }}
